:mkdir vinnytsia
mkdir dnipro
mkdir donetsk
mkdir zhytomyr
mkdir zaporizhzhia
mkdir ivano-frankivsk
mkdir kyiv
mkdir kropyvnytskyi
mkdir luhansk
mkdir lutsk
mkdir lviv
mkdir mykolaiv
mkdir odesa
mkdir poltava
mkdir rivne
mkdir sevastopol
mkdir simferopol
mkdir sumy
mkdir ternopil
mkdir uzhhorod
mkdir kharkiv
mkdir kherson
mkdir khmelnytskyi
mkdir cherkasy
mkdir chernivtsi
mkdir chernihiv